authorName: default
experimentName: brain_cls_nni_crop
trialConcurrency: 24
maxExecDuration: 10000h
maxTrialNum: 3000
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space.json
logDir: /staff/haoxiaoyu/workspace/brain_cls/brain_cls_nni_log_crop
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: maximize
trial:
  command: python nni_run.py
  codeDir: /staff/haoxiaoyu/workspace/brain_cls
  gpuNum: 1
localConfig:
  gpuIndices: "0,1,2,3,4,5"
  useActiveGpu: True
  maxTrialNumPerGpu: 4